apiVersion: config.openshift.io/v1
kind: ClusterOperator
metadata:
  name: authentication

## ArgoCD Lua script to check health
## Add it to ArgoCD resource spec/resourceCustomizations
## See also https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#resource-customizations-example
#config.openshift.io/ClusterOperator:
#  health.lua: |
#    hs = {}
#    hs.status = "Progressing"
#    hs.message = ""
#    if obj.status ~= nil then
#      if obj.status.conditions ~= nil then
#        for i, condition in ipairs(obj.status.conditions) do
#          if condition.type == "Progressing" and condition.status == "True" then
#            hs.status = "Progressing"
#            hs.message = condition.message
#            return hs
#          end
#          if condition.type == "Progressing" and condition.status == "False" then
#            for y, cond in ipairs(obj.status.conditions) do
#             if cond.type == "Available" and cond.status == "True" then
#               hs.status = "Healthy"
#               hs.message = condition.message
#               return hs
#             end
#            end
#          end
#        end
#      end
#    end
#    return hs
