kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=false
data:
  clientSecret: UGtrN3JOVEhTdUV3WDJkZGd5aTB0WkVYQjFIMnRLSVo=
type: Opaque