kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: Validate=false
data:
  clientSecret: elJqRTU5SlZpejBuTjFaV044elVxTGFTT0dUWm91SnI=
type: Opaque