apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    argocd.argoproj.io/sync-options: Validate=false
spec:
  identityProviders:
    - mappingMethod: claim
      name: keycloak
      openID:
        ca:
          name: keycloak-ca
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: ocp
        clientSecret:
          name: keycloak-secret
        extraScopes: []
        issuer: >-
          https://keycloak-default.apps.rw-east.c14h.p1.openshiftapps.com/realms/master
      type: OpenID
  tokenConfig: {}
