apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - mappingMethod: claim
      name: keycloak
      openID:
        ca:
          name: keycloak-ca
        claims:
          email:
            - email
          name:
            - name
          preferredUsername:
            - preferred_username
        clientID: ocp
        clientSecret:
          name: keycloak-secret
        extraScopes: []
        issuer: >-
          https://keycloak-default.apps.rw-east.c14h.p1.openshiftapps.com/realms/master/protocol/openid-connect/auth
      type: OpenID
  tokenConfig: {}
